[package]
name = "todo-list"
version = "1.0.0"
repository = "https://github.com/PepeePL/todo-list"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "4.0.0"

[build]
